repos:
-   repo: local
    hooks:
    - id: strip_kernel
      name: strip_kernel
      entry: bash 'docs/precommit_strip_kernel.sh'
      language: system
      types: [python]
      pass_filenames: false
-   repo: https://github.com/pycqa/isort
    rev: 5.10.0
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
