name: ahlive-ci

channels:
 - conda-forge

dependencies:
  - cartopy
  - gifsicle
  - pandoc
  - pip
  - pip:
    - sphinx
    - nbsphinx
    - sphinx-book-theme
    - ipykernel
    - ipywidgets
    - widgetsnbextension
    - panel
    - pooch
    - pygifsicle
    - pre-commit
    - pytest
    - -e ..
