name: ahlive-ci

channels:
 - conda-forge

dependencies:
  - python=3.7
  - cartopy=0.18.0
  - gifsicle
  - pip
  - pip:
    - sphinx
    - nbsphinx
    - sphinx-book-theme
    - ipykernel
    - panel
    - pygifsicle
    - pytest
    - pandoc