name: ahlive-docs

channels:
 - conda-forge

dependencies:
  - python
  - cartopy
  - gifsicle
  - pip
  - pip:
    - sphinx
    - nbsphinx
    - sphinx-book-theme
    - ipykernel
    - jupyter
    - ipywidgets
    - panel
    - pygifsicle
    - pooch
    - adjustText
