name: Lint

on: pull_request

jobs:
  lint:  # Runs linting package checks for code styling.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Lint with flake8
        shell: bash -l {0}
        run: |
          pip install flake8
          flake8 ahlive
      - name: Lint with black
        shell: bash -l {0}
        run: |
          pip install black
          black --check ahlive
      - name: Lint with isort
        shell: bash -l {0}
        run: |
          pip install isort
          isort --check-only ahlive
