name: ahlive testing

on: pull_request_target

jobs:
  test:  # Runs testing suite on various python versions.
    name: Test ahlive, python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Install Conda environment
        uses: conda-incubator/setup-miniconda@v1
        with:
          auto-update-conda: true
          activate-environment: ahlive-docs
          environment-file: docs/environment_rtd.yml
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: Run tests
        shell: bash -l {0}
        run: |
          conda activate ahlive-minimum-tests
          pytest --cov=ahlive --cov-report=xml

  docs_notebooks:  # Checks that pre-compiled notebooks in docs still work.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Conda environment
        uses: conda-incubator/setup-miniconda@v1
        with:
          auto-update-conda: true
          activate-environment: ahlive-docs
          environment-file: environment_rtd.yml
          python-version: 3.6
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: Test notebooks in docs
        shell: bash -l {0}
        run: |
          pushd docs
          make html
          popd
